package errors

const (
	Unauthorized             = "401001"
	NotFoundError            = "404001"
	IsRequired               = "422001"
	FormatIsInvalid          = "422002"
	IsInvalid                = "422003"
	IsAlreadyExist           = "422004"
	IsNotFound               = "422005"
	ConfigurationIsNotFound  = "422006"
	UnhandledError           = "500999"
	BodyParserError          = "400001"
	ErrorUnprocessableEntity = "ERROR_UNPROCESSABLE_ENTITY"
)

var (
	TagValidators = map[string]string{
		"required":                      IsRequired,
		"required_if":                   IsRequired,
		"required_unless":               IsRequired,
		"skip_unless":                   IsRequired,
		"required_with":                 IsRequired,
		"required_with_all":             IsRequired,
		"required_without":              IsRequired,
		"required_without_all":          IsRequired,
		"excluded_if":                   IsRequired,
		"excluded_unless":               IsRequired,
		"excluded_with":                 IsRequired,
		"excluded_with_all":             IsRequired,
		"excluded_without":              IsRequired,
		"excluded_without_all":          IsRequired,
		"isdefault":                     IsRequired,
		"regexp":                        IsRequired,
		"len":                           IsInvalid,
		"min":                           IsInvalid,
		"max":                           IsInvalid,
		"eq":                            IsInvalid,
		"eq_ignore_case":                IsInvalid,
		"ne":                            IsInvalid,
		"ne_ignore_case":                IsInvalid,
		"lt":                            IsInvalid,
		"lte":                           IsInvalid,
		"gt":                            IsInvalid,
		"gte":                           IsInvalid,
		"eqfield":                       IsInvalid,
		"eqcsfield":                     IsInvalid,
		"necsfield":                     IsInvalid,
		"gtcsfield":                     IsInvalid,
		"gtecsfield":                    IsInvalid,
		"ltcsfield":                     IsInvalid,
		"ltecsfield":                    IsInvalid,
		"nefield":                       IsInvalid,
		"gtefield":                      IsInvalid,
		"gtfield":                       IsInvalid,
		"ltefield":                      IsInvalid,
		"ltfield":                       IsInvalid,
		"fieldcontains":                 IsInvalid,
		"fieldexcludes":                 IsInvalid,
		"alpha":                         FormatIsInvalid,
		"alphanum":                      FormatIsInvalid,
		"alphaunicode":                  FormatIsInvalid,
		"alphanumunicode":               FormatIsInvalid,
		"boolean":                       FormatIsInvalid,
		"numeric":                       FormatIsInvalid,
		"number":                        FormatIsInvalid,
		"hexadecimal":                   FormatIsInvalid,
		"hexcolor":                      FormatIsInvalid,
		"rgb":                           FormatIsInvalid,
		"rgba":                          FormatIsInvalid,
		"hsl":                           FormatIsInvalid,
		"hsla":                          FormatIsInvalid,
		"e164":                          FormatIsInvalid,
		"email":                         FormatIsInvalid,
		"url":                           FormatIsInvalid,
		"http_url":                      FormatIsInvalid,
		"uri":                           FormatIsInvalid,
		"urn_rfc2141":                   FormatIsInvalid, // RFC 2141
		"file":                          FormatIsInvalid,
		"filepath":                      FormatIsInvalid,
		"base64":                        FormatIsInvalid,
		"base64url":                     FormatIsInvalid,
		"base64rawurl":                  FormatIsInvalid,
		"contains":                      FormatIsInvalid,
		"containsany":                   FormatIsInvalid,
		"containsrune":                  FormatIsInvalid,
		"excludes":                      FormatIsInvalid,
		"excludesall":                   FormatIsInvalid,
		"excludesrune":                  FormatIsInvalid,
		"startswith":                    FormatIsInvalid,
		"endswith":                      FormatIsInvalid,
		"startsnotwith":                 FormatIsInvalid,
		"endsnotwith":                   FormatIsInvalid,
		"image":                         FormatIsInvalid,
		"isbn":                          FormatIsInvalid,
		"isbn10":                        FormatIsInvalid,
		"isbn13":                        FormatIsInvalid,
		"eth_addr":                      FormatIsInvalid,
		"eth_addr_checksum":             FormatIsInvalid,
		"btc_addr":                      FormatIsInvalid,
		"btc_addr_bech32":               FormatIsInvalid,
		"uuid":                          FormatIsInvalid,
		"uuid3":                         FormatIsInvalid,
		"uuid4":                         FormatIsInvalid,
		"uuid5":                         FormatIsInvalid,
		"uuid_rfc4122":                  FormatIsInvalid,
		"uuid3_rfc4122":                 FormatIsInvalid,
		"uuid4_rfc4122":                 FormatIsInvalid,
		"uuid5_rfc4122":                 FormatIsInvalid,
		"ulid":                          FormatIsInvalid,
		"md4":                           FormatIsInvalid,
		"md5":                           FormatIsInvalid,
		"sha256":                        FormatIsInvalid,
		"sha384":                        FormatIsInvalid,
		"sha512":                        FormatIsInvalid,
		"ripemd128":                     FormatIsInvalid,
		"ripemd160":                     FormatIsInvalid,
		"tiger128":                      FormatIsInvalid,
		"tiger160":                      FormatIsInvalid,
		"tiger192":                      FormatIsInvalid,
		"ascii":                         FormatIsInvalid,
		"printascii":                    FormatIsInvalid,
		"multibyte":                     FormatIsInvalid,
		"datauri":                       FormatIsInvalid,
		"latitude":                      FormatIsInvalid,
		"longitude":                     FormatIsInvalid,
		"ssn":                           FormatIsInvalid,
		"ipv4":                          FormatIsInvalid,
		"ipv6":                          FormatIsInvalid,
		"ip":                            FormatIsInvalid,
		"cidrv4":                        FormatIsInvalid,
		"cidrv6":                        FormatIsInvalid,
		"cidr":                          FormatIsInvalid,
		"tcp4_addr":                     FormatIsInvalid,
		"tcp6_addr":                     FormatIsInvalid,
		"tcp_addr":                      FormatIsInvalid,
		"udp4_addr":                     FormatIsInvalid,
		"udp6_addr":                     FormatIsInvalid,
		"udp_addr":                      FormatIsInvalid,
		"ip4_addr":                      FormatIsInvalid,
		"ip6_addr":                      FormatIsInvalid,
		"ip_addr":                       FormatIsInvalid,
		"unix_addr":                     FormatIsInvalid,
		"mac":                           FormatIsInvalid,
		"hostname":                      FormatIsInvalid, // RFC 952
		"hostname_rfc1123":              FormatIsInvalid, // RFC 1123
		"fqdn":                          FormatIsInvalid,
		"unique":                        IsInvalid,
		"oneof":                         IsInvalid,
		"html":                          FormatIsInvalid,
		"html_encoded":                  FormatIsInvalid,
		"url_encoded":                   FormatIsInvalid,
		"dir":                           FormatIsInvalid,
		"dirpath":                       FormatIsInvalid,
		"json":                          FormatIsInvalid,
		"jwt":                           FormatIsInvalid,
		"hostname_port":                 FormatIsInvalid,
		"lowercase":                     FormatIsInvalid,
		"uppercase":                     FormatIsInvalid,
		"datetime":                      FormatIsInvalid,
		"timezone":                      FormatIsInvalid,
		"iso3166_1_alpha2":              FormatIsInvalid,
		"iso3166_1_alpha3":              FormatIsInvalid,
		"iso3166_1_alpha_numeric":       FormatIsInvalid,
		"iso3166_2":                     FormatIsInvalid,
		"iso4217":                       FormatIsInvalid,
		"iso4217_numeric":               FormatIsInvalid,
		"bcp47_language_tag":            FormatIsInvalid,
		"postcode_iso3166_alpha2":       FormatIsInvalid,
		"postcode_iso3166_alpha2_field": FormatIsInvalid,
		"bic":                           FormatIsInvalid,
		"semver":                        FormatIsInvalid,
		"dns_rfc1035_label":             FormatIsInvalid,
		"credit_card":                   FormatIsInvalid,
		"cve":                           FormatIsInvalid,
		"luhn_checksum":                 FormatIsInvalid,
		"mongodb":                       FormatIsInvalid,
		"cron":                          FormatIsInvalid,
	}
)
